disallowed-methods = [
    "std::fs::canonicalize",
    "std::fs::copy",
    "std::fs::create_dir",
    "std::fs::create_dir_all",
    "std::fs::exists",
    "std::fs::hard_link",
    "std::fs::metadata",
    "std::fs::read",
    "std::fs::read_dir",
    "std::fs::read_link",
    "std::fs::read_to_string",
    "std::fs::remove_dir",
    "std::fs::remove_dir_all",
    "std::fs::remove_file",
    "std::fs::rename",
    "std::fs::set_permissions",
    "std::fs::soft_link",
    "std::fs::symlink_metadata",
    "std::fs::write",
    "std::path::Path::try_exists",
    "std::path::Path::metadata",
    "std::path::Path::symlink_metadata",
    "std::path::Path::canonicalize",
    "std::path::Path::read_link",
    "std::path::Path::read_dir",
    "std::path::Path::is_dir",
    "std::path::Path::is_file",
    "std::path::Path::is_symlink",
    "std::path::Path::exists",
]

disallowed-types = [
    "std::fs::DirEntry",
    "std::fs::File",
    "std::fs::FileType",
    "std::fs::Metadata",
    "std::fs::OpenOptions",
    "std::fs::Permissions",
    "std::fs::ReadDir",
]
