on:
  push:
  pull_request:

name: Continuous integration

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
        args:
          - '--no-default-features'
        include:
          - rust: nightly
            args: '--features backtrace'

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9 # master
        with:
          toolchain: ${{ matrix.rust }}
          components: rustfmt, clippy

      - run: cargo build ${{ matrix.args }}

      - run: cargo test ${{ matrix.args }}

      - run: cargo fmt --all -- --check

      - run: cargo clippy ${{ matrix.args }} -- -D warnings

      - uses: EmbarkStudios/cargo-deny-action@6c8f9facfa5047ec02d8485b6bf52b587b7777d1 # v2
